# Generated by Django 5.0.1 on 2024-02-29 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_confirmationpage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConfirmationPage',
        ),
    ]
