# Generated by Django 5.0.1 on 2024-04-09 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_remove_payment_person_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='person_name',
            field=models.CharField(default='Anonymous', max_length=100),
        ),
    ]
