# Generated by Django 5.0.1 on 2024-05-08 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_remove_payment_amount_remove_payment_payment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='Person_name',
            field=models.CharField(default='Default Name', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='card_number',
            field=models.CharField(default='Default Name', max_length=15),
        ),
        migrations.AddField(
            model_name='payment',
            name='cvv',
            field=models.CharField(default='Default Name', max_length=3),
        ),
        migrations.AddField(
            model_name='payment',
            name='expiry',
            field=models.DateField(default='Default Name', max_length=5),
        ),
    ]
