# Generated by Django 5.0.1 on 2024-05-08 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_payment_my_char_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='my_char_field',
        ),
    ]
