# Generated by Django 5.0.1 on 2024-05-08 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_remove_payment_my_char_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='expiry',
            field=models.DateField(default='2024-12-31'),
        ),
    ]
