# Generated by Django 5.0.1 on 2024-05-08 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_alter_payment_expiry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='expiry',
            new_name='expiry_date',
        ),
    ]
