# Generated by Django 5.0.1 on 2024-05-08 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_remove_payment_payment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_date',
            field=models.DateTimeField(default='2024-05-08 08:30:00'),
        ),
    ]
