# Generated by Django 5.0.1 on 2024-05-09 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_alter_payment_payment_date'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='payment',
        #     name='amount',
        # ),
        # migrations.RemoveField(
        #     model_name='payment',
        #     name='payment_date',
        # ),
        # migrations.RemoveField(
        #     model_name='payment',
        #     name='payment_method',
        # ),
        migrations.AddField(
            model_name='payment',
            name='card_number',
            field=models.CharField(default='DEFAULT_CARD_NUMBER', max_length=16),
        ),
        migrations.AddField(
            model_name='payment',
            name='cvv',
            field=models.CharField(default='DEFAULT_CVV', max_length=4),
        ),
        migrations.AddField(
            model_name='payment',
            name='expiry_date',
            field=models.CharField(default='DEFAULT_EXPIRY_DATE', max_length=5),
        ),
    ]
