# Generated by Django 5.0.1 on 2024-05-09 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_remove_payment_amount_remove_payment_payment_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_date',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_method',
        ),
    ]
