# Generated by Django 5.0.1 on 2024-05-09 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_remove_payment_amount_remove_payment_payment_date_and_more'),
    ]

    # operations = [
    #     migrations.AddField(
    #         model_name='payment',
    #         name='person_name',
    #         field=models.CharField(default='', max_length=16),
    #     ),
    #     migrations.AlterField(
    #         model_name='payment',
    #         name='card_number',
    #         field=models.CharField(default='', max_length=16),
    #     ),
    #     migrations.AlterField(
    #         model_name='payment',
    #         name='cvv',
    #         field=models.CharField(default='', max_length=4),
    #     ),
    #     migrations.AlterField(
    #         model_name='payment',
    #         name='expiry_date',
    #         field=models.CharField(default='', max_length=5),
    #     ),
    # ]
