# Generated by Django 5.0.1 on 2024-05-09 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_payment_person_name_alter_payment_card_number_and_more'),
    ]

    operations = [
      
        migrations.AddField(
            model_name='payment',
            name='payment_date',
            field=models.DateTimeField(default='2024-05-09 01:29:00'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(default='', max_length=20),
        ),
    ]
