# Generated by Django 5.0.1 on 2024-05-09 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_remove_payment_card_number_remove_payment_cvv_and_more'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='payment',
        #     name='card_number',
        # ),
        # migrations.RemoveField(
        #     model_name='payment',
        #     name='cvv',
        # ),
        # migrations.RemoveField(
        #     model_name='payment',
        #     name='expiry_date',
        # ),
        migrations.AddField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
