# Generated by Django 5.0.1 on 2024-05-09 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_remove_payment_card_number_remove_payment_cvv_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='card_number',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='cvv',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='expiry_date',
        ),
    ]
