# Generated by Django 5.0.1 on 2024-05-09 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_remove_payment_card_number_remove_payment_cvv_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='payment_date',
        ),
    ]
