# Generated by Django 5.0.1 on 2024-05-09 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_remove_payment_payment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_date',
            field=models.DateTimeField(default='2024-05-09 01:29:00'),
        ),
    ]
